'use strict';
const $ = s => document.querySelector(s);
const state = {cards: [], families: [], family: 'all', reading: [], kind: '', journal: []};
const escapeHTML = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm = s => s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function toast(message) { $('#status').textContent = message; clearTimeout(toast.timer); toast.timer = setTimeout(() => $('#status').textContent = '', 4500); }
function readStore(key, fallback) { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }
function store(key, value) { try { localStorage.setItem(key, JSON.stringify(value)); return true; } catch { toast('Le stockage est indisponible. Votre note n’a pas été enregistrée.'); return false; } }
function dayKey() { const d = new Date(); return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`; }
function randomIndex(n) { const a = new Uint32Array(1); const limit = Math.floor(4294967296/n)*n; do { crypto.getRandomValues(a); } while(a[0]>=limit); return a[0]%n; }
function navigate(name) { document.querySelectorAll('.view').forEach(v => v.hidden = v.id !== name); document.querySelectorAll('[data-view]').forEach(b => { if(b.dataset.view === name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current'); }); if(name==='journal')renderJournal(); window.scrollTo(0,0); }
document.querySelectorAll('[data-view]').forEach(b => b.onclick = () => navigate(b.dataset.view));
$('.brand').onclick = e => {e.preventDefault();navigate('rituel');};
$('#today').textContent = new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long'}).format(new Date()).toUpperCase();
function renderFilters() { $('#filters').innerHTML = [{key:'all',short:'Toutes'},...state.families].map(f => `<button data-family="${escapeHTML(f.key)}" aria-pressed="${f.key===state.family}">${escapeHTML(f.short||f.name)}</button>`).join(''); }
function renderCards() { const q = norm($('#search').value); const cards = state.cards.filter(c => (state.family === 'all'||c.fam===state.family) && norm(c.name).includes(q)); $('#count').textContent = `${cards.length} carte${cards.length>1?'s':''}`; $('#grid').innerHTML = cards.map(c => `<button class="card" data-card="${c.id}" aria-label="Découvrir ${escapeHTML(c.name)}"><img src="img/${c.id}.jpg" alt="" loading="lazy"><span>${escapeHTML(c.name)}</span></button>`).join('') || '<p class="empty">Aucune carte. Essayez un autre nom ou une autre famille.</p>'; }
$('#search').oninput = renderCards;
$('#filters').onclick = e => {const b=e.target.closest('[data-family]');if(b){state.family=b.dataset.family;renderFilters();renderCards();}};
$('#grid').onclick = e => {const b=e.target.closest('[data-card]');if(b)openReading([b.dataset.card],'Découverte',false);};
function sections(html) { const doc = new DOMParser().parseFromString(html,'text/html'); return [...doc.querySelectorAll('section')].map(s => `<details><summary>${escapeHTML(s.querySelector('h2')?.textContent || 'En savoir plus')}</summary>${[...s.querySelectorAll('p')].map(p=>`<p>${escapeHTML(p.textContent)}</p>`).join('')}</details>`).join(''); }
function openReading(ids,kind,save=true) { state.reading=ids;state.kind=kind;$('#detail-label').textContent=kind;$('#note').value='';$('#save').disabled=false;$('#save').textContent='Enregistrer dans mon journal';$('#journal-form').hidden=!save;const labels=['Situation','Éclairage','Piste à explorer'];$('#reading').innerHTML=ids.map((id,i)=>{const c=state.cards.find(c=>c.id===id);return `<article class="reading-card">${ids.length>1?`<p class="eyebrow">${labels[i]}</p>`:''}<img src="img/${c.id}.jpg" alt="${escapeHTML(c.name)}"><h2>${escapeHTML(c.name)}</h2><p class="keywords">${escapeHTML((c.keywords_up||'').split(',').slice(0,4).join(' · '))}</p><p class="guidance">${escapeHTML(c.cod)}</p>${sections(c.html)}</article>`;}).join('');$('#detail').showModal();$('#detail').scrollTop=0; }
$('#daily').onclick=()=>{const key=dayKey();let daily=readStore('tarot.daily',null);if(!daily||daily.day!==key||!state.cards.some(c=>c.id===daily.id)){daily={day:key,id:state.cards[randomIndex(state.cards.length)].id};store('tarot.daily',daily);}openReading([daily.id],'La carte du jour');};
$('#spread-start').onclick=()=>{const pool=[...state.cards];const ids=Array.from({length:3},()=>pool.splice(randomIndex(pool.length),1)[0].id);openReading(ids,'Le tirage à trois cartes');};
$('#close-detail').onclick=()=>$('#detail').close();$('#settings').onclick=()=>$('#about').showModal();$('#close-about').onclick=()=>$('#about').close();
$('#save').onclick=()=>{const entry={id:crypto.randomUUID(),date:new Date().toISOString(),kind:state.kind,cards:[...state.reading],note:$('#note').value.trim()};const next=[entry,...state.journal];if(store('tarot.journal',next)){state.journal=next;$('#detail').close();navigate('journal');toast('Votre tirage a été enregistré.');}};
function renderJournal(){ $('#erase').hidden=!state.journal.length;$('#entries').innerHTML=state.journal.map(e=>`<article class="entry"><span class="eyebrow">${escapeHTML(new Date(e.date).toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'}))}</span><h2>${escapeHTML(e.kind)}</h2><div class="entry-images">${e.cards.map(id=>`<img src="img/${id}.jpg" alt="${escapeHTML(state.cards.find(c=>c.id===id).name)}">`).join('')}</div><p>${escapeHTML(e.note||'Un moment à laisser résonner.')}</p><button class="outline" data-open="${escapeHTML(e.id)}">Relire les cartes</button> <button class="outline" data-delete="${escapeHTML(e.id)}" aria-label="Supprimer ce tirage">Supprimer</button></article>`).join('')||'<div class="empty"><h2>La première page est à vous.</h2><p>Tirez une carte, notez ce qu’elle vous inspire et enregistrez votre lecture ici.</p><button class="outline" id="first-draw">Faire mon premier tirage</button></div>';if($('#first-draw'))$('#first-draw').onclick=()=>navigate('rituel'); }
$('#entries').onclick=e=>{const o=e.target.closest('[data-open]'),d=e.target.closest('[data-delete]');if(o){const entry=state.journal.find(x=>x.id===o.dataset.open);openReading(entry.cards,entry.kind,false);}if(d&&confirm('Supprimer ce tirage et sa note ?')){const next=state.journal.filter(x=>x.id!==d.dataset.delete);if(store('tarot.journal',next)){state.journal=next;renderJournal();}}};
$('#erase').onclick=()=>{if(confirm('Effacer tous les tirages et toutes les notes ? Cette action est définitive.')&&store('tarot.journal',[])){state.journal=[];renderJournal();}};
fetch('app-data.json').then(r=>{if(!r.ok)throw Error('data');return r.json();}).then(data=>{if(data.cards?.length!==78)throw Error('cards');state.cards=data.cards;state.families=data.families;const saved=readStore('tarot.journal',[]);state.journal=Array.isArray(saved)?saved.filter(e=>e&&Array.isArray(e.cards)&&e.cards.length&&e.cards.every(id=>state.cards.some(c=>c.id===id))):[];renderFilters();renderCards();$('#daily').disabled=false;$('#spread-start').disabled=false;}).catch(()=>toast('Les cartes n’ont pas pu être chargées. Fermez puis rouvrez l’application.'));
